### ISSUE TITLE
Steam Authentication Problem

### ISSUE THREAD

**Issue by KirbyTheG** [JBEP3/jbep3_dev#1]
When ever I try to run a server or just run one of the maps the game kicks me out and gives me a `Disconnect: Auth Failure (1).` 
Any workarounds?

**Comment by zxz41** [comment]
Are you part of the closed beta Steam group?
Are you using a Listen Server (Hosting from in-game) or Dedicated Server (srcds)?

**Comment by KirbyTheG** [comment]
From what I heard the mod has stopped development and the code is open use. Also I was hosting in-game.

**Comment by zxz41** [comment]
Nope, the thing still require you to be in the close beta group. [They said they would make a open Source version at some point and move on to Unreal Engine 4](https://www.facebook.com/JBEP3/posts/851757264861219)

**Comment by KirbyTheG** [comment]
Any way around it?

**Comment by deadhunt49** [comment]
there is....but cracking client.dll and remove the DRM

**Comment by deadhunt49** [comment]
there is a way around by using smartsteamemu

**Comment by CabooseJr** [comment]
https://store.steampowered.com/app/869480/Jabroni_Brawl_Episode_3/

**Comment by Axteus** [comment]
Nevermind, all I had to do was turn my internet off while playing.
